// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class Bodega
    {
        public Bodega()
        {
            CentroEducativo = new HashSet<CentroEducativo>();
            Programacion = new HashSet<Programacion>();
            Users = new HashSet<Users>();
            WayBill = new HashSet<WayBill>();
        }

        public int Id { get; set; }
        [Display(Name = "Departamento")]
        public int IdDepartamento { get; set; }
        [Display(Name = "Municipio")]
        public int IdMunicipio { get; set; }
        [Display(Name = "Distrito")]
        public int IdDistrito { get; set; }
        [Display(Name = "Sub Oficina")]
        public int IdSubOficina { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }
        [StringLength(150)]
        [Display(Name = "Dirección")]
        public string Direccion { get; set; }
        [Required]
        [StringLength(100)]
        public string Responsable { get; set; }
        [StringLength(10)]
        [Display(Name = "Teléfono del Responsable")]
        public string TelefonoResponsable { get; set; }
        [StringLength(100)]
        [Display(Name = "Responsable alterno")]
        public string Responsable2 { get; set; }
        [StringLength(14)]
        [Display(Name = "Teléfono Responsable alterno")]
        public string TelefonoResponsable2 { get; set; }
        [Required]
        public bool? Estado { get; set; }

        [Display(Name = "Departamento")]
        [ForeignKey("IdDepartamento")]
        [InverseProperty("Bodega")]
        public virtual Departamento IdDepartamentoNavigation { get; set; }
        [ForeignKey("IdDistrito")]
        [InverseProperty("Bodega")]
        [Display(Name = "Distrito")]
        public virtual Distrito IdDistritoNavigation { get; set; }
        [ForeignKey("IdMunicipio")]
        [InverseProperty("Bodega")]
        [Display(Name = "Municipio")]
        public virtual Municipio IdMunicipioNavigation { get; set; }
        [ForeignKey("IdSubOficina")]
        [InverseProperty("Bodega")]
        [Display(Name = "Sub Oficina")]
        public virtual SubOficina IdSubOficinaNavigation { get; set; }
        [InverseProperty("IdBodegaNavigation")]
        public virtual ICollection<CentroEducativo> CentroEducativo { get; set; }
        [InverseProperty("IdBodegaNavigation")]
        public virtual ICollection<Programacion> Programacion { get; set; }

        [InverseProperty("IdBodegaNavigation")]
        public virtual ICollection<Users> Users { get; set; }
        [InverseProperty("IdBodegaNavigation")]
        public virtual ICollection<WayBill> WayBill { get; set; }
    }
}