// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class Departamento
    {
        public Departamento()
        {
            Bodega = new HashSet<Bodega>();
            CentroEducativo = new HashSet<CentroEducativo>();
            Distrito = new HashSet<Distrito>();
            Municipio = new HashSet<Municipio>();
            Programacion = new HashSet<Programacion>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(2)]
        public string Codigo { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }

        [InverseProperty("IdDepartamentoNavigation")]
        public virtual ICollection<Bodega> Bodega { get; set; }
        [InverseProperty("IdDepartamentoNavigation")]
        public virtual ICollection<CentroEducativo> CentroEducativo { get; set; }
        [InverseProperty("IdDepartamentoNavigation")]
        public virtual ICollection<Distrito> Distrito { get; set; }
        [InverseProperty("Departamento")]
        public virtual ICollection<Municipio> Municipio { get; set; }
        [InverseProperty("IdDepartamentoNavigation")]
        public virtual ICollection<Programacion> Programacion { get; set; }
    }
}