// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class Distrito
    {
        public Distrito()
        {
            Bodega = new HashSet<Bodega>();
            CentroEducativo = new HashSet<CentroEducativo>();
        }

        public int Id { get; set; }
        [Display(Name = "Departamento")]
        public int IdDepartamento { get; set; }
        [Required]
        [StringLength(30)]
        public string Nombre { get; set; }
        [StringLength(800)]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        [Required]
        public bool? Estado { get; set; }

        [ForeignKey("IdDepartamento")]
        [InverseProperty("Distrito")]
        [Display(Name = "Departamento")]
        public virtual Departamento IdDepartamentoNavigation { get; set; }
        [InverseProperty("IdDistritoNavigation")]        
        public virtual ICollection<Bodega> Bodega { get; set; }
        [InverseProperty("IdDistritoNavigation")]
        public virtual ICollection<CentroEducativo> CentroEducativo { get; set; }
    }
}