// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class Focalizacion
    {
        public Focalizacion()
        {
            Programacion = new HashSet<Programacion>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }
        public bool Estado { get; set; }

        [InverseProperty("IdFocalizacionNavigation")]
        public virtual ICollection<Programacion> Programacion { get; set; }
    }
}