// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class Producto
    {
        public Producto()
        {
            NotaRemision = new HashSet<NotaRemision>();
            ProgramacionProductoDetalle = new HashSet<ProgramacionProductoDetalle>();
            RacionDetalle = new HashSet<RacionDetalle>();
            WayBillDetalle = new HashSet<WayBillDetalle>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }
        public int? EmbalajeId { get; set; }

        [ForeignKey("EmbalajeId")]
        [InverseProperty("Producto")]
        public virtual Embalaje Embalaje { get; set; }
        [InverseProperty("IdProductoNavigation")]
        public virtual ICollection<NotaRemision> NotaRemision { get; set; }
        [InverseProperty("IdProductoNavigation")]
        public virtual ICollection<ProgramacionProductoDetalle> ProgramacionProductoDetalle { get; set; }
        [InverseProperty("IdProductoNavigation")]
        public virtual ICollection<RacionDetalle> RacionDetalle { get; set; }
        [InverseProperty("IdProductoNavigation")]
        public virtual ICollection<WayBillDetalle> WayBillDetalle { get; set; }
    }
}