// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class ProgramacionProductoDetalle
    {
        public int Id { get; set; }
        [Display(Name = "Programación")]
        public int IdProgramacion { get; set; }
        [Required]
        [StringLength(20)]
        [Display(Name = "Centro Educativo")]
        public string IdCentroEducativo { get; set; }
        [Display(Name = "Producto")]
        public int IdProducto { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Cantidad { get; set; }

        [ForeignKey("IdCentroEducativo")]
        [InverseProperty("ProgramacionProductoDetalle")]
        [Display(Name = "Centro Educativo")]
        public virtual CentroEducativo IdCentroEducativoNavigation { get; set; }
        [ForeignKey("IdProducto")]
        [InverseProperty("ProgramacionProductoDetalle")]
        [Display(Name = "Producto")]
        public virtual Producto IdProductoNavigation { get; set; }
        [ForeignKey("IdProgramacion")]
        [InverseProperty("ProgramacionProductoDetalle")]
        [Display(Name = "Programación")]
        public virtual Programacion IdProgramacionNavigation { get; set; }
    }
}