// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class Programacion
    {
        public Programacion()
        {
            NotaRemision = new HashSet<NotaRemision>();
            ProgramacionCentroEducativo = new HashSet<ProgramacionCentroEducativo>();
            ProgramacionProductoDetalle = new HashSet<ProgramacionProductoDetalle>();
        }

        public int Id { get; set; }
        [Display(Name = "Remesa")]
        public int IdRemesa { get; set; }
        [Display(Name = "Departamento")]
        public int? IdDepartamento { get; set; }
        [Display(Name = "Municipio")]
        public int? IdMunicipio { get; set; }
        [Display(Name = "Bodega")]
        public int? IdBodega { get; set; }
        [Display(Name = "Focalización")]
        public int IdFocalizacion { get; set; }
        [Column(TypeName = "date")]
        public DateTime Fecha { get; set; }
        [Required]
        [StringLength(1)]
        [Display(Name = "Activo")]
        public string Estado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaCreacion { get; set; }
        
        [StringLength(450)]
        public string UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaModificacion { get; set; }
        
        [StringLength(450)]
        public string UsuarioModificacion { get; set; }

        [ForeignKey("IdBodega")]
        [InverseProperty("Programacion")]
        [Display(Name = "Bodega")]
        public virtual Bodega IdBodegaNavigation { get; set; }
        [ForeignKey("IdDepartamento")]
        [InverseProperty("Programacion")]
        [Display(Name = "Departamento")]
        public virtual Departamento IdDepartamentoNavigation { get; set; }
        [ForeignKey("IdFocalizacion")]
        [InverseProperty("Programacion")]
        [Display(Name = "Focalización")]
        public virtual Focalizacion IdFocalizacionNavigation { get; set; }
        [ForeignKey("IdMunicipio")]
        [InverseProperty("Programacion")]
        [Display(Name = "Municipio")]
        public virtual Municipio IdMunicipioNavigation { get; set; }
        [ForeignKey("IdRemesa")]
        [InverseProperty("Programacion")]
        [Display(Name = "Remesa")]
        public virtual Remesa IdRemesaNavigation { get; set; }
        [InverseProperty("IdProgramacionNavigation")]
        public virtual ICollection<NotaRemision> NotaRemision { get; set; }
        [InverseProperty("IdProgramacionNavigation")]
        public virtual ICollection<ProgramacionCentroEducativo> ProgramacionCentroEducativo { get; set; }
        [InverseProperty("IdProgramacionNavigation")]
        public virtual ICollection<ProgramacionProductoDetalle> ProgramacionProductoDetalle { get; set; }
    }
}