// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class ProgramacionCentroEducativo
    {
        public int Id { get; set; }
        [Display(Name = "Programación")]
        public int IdProgramacion { get; set; }
        [Required]
        [StringLength(20)]
        [Display(Name = "Centro Educativo")]
        public string IdCentroEducativo { get; set; }
        [Display(Name = "Niños")]
        public int Ninos { get; set; }
        [Display(Name = "Niñas")]
        public int Ninas { get; set; }
        public int Total { get; set; }

        [ForeignKey("IdCentroEducativo")]
        [InverseProperty("ProgramacionCentroEducativo")]
        [Display(Name = "Centro Educativo")]
        public virtual CentroEducativo IdCentroEducativoNavigation { get; set; }
        [ForeignKey("IdProgramacion")]
        [InverseProperty("ProgramacionCentroEducativo")]
        [Display(Name = "Programación")]
        public virtual Programacion IdProgramacionNavigation { get; set; }
    }
}