// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class Racion
    {
        public Racion()
        {
            RacionDetalle = new HashSet<RacionDetalle>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }
        [Display(Name = "Zona")]
        public int IdZona { get; set; }
        [Required]
        [StringLength(40)]
        public string Nivel { get; set; }
        [Required]
        public bool? Estado { get; set; }

        [ForeignKey("IdZona")]
        [InverseProperty("Racion")]
        [Display(Name = "Zona")]
        public virtual Zona IdZonaNavigation { get; set; }
        [InverseProperty("IdRacionNavigation")]
        public virtual ICollection<RacionDetalle> RacionDetalle { get; set; }
    }
}