// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class Remesa
    {
        public Remesa()
        {
            Programacion = new HashSet<Programacion>();
            WayBill = new HashSet<WayBill>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }
        [Display(Name = "Año")]
        public int Ano { get; set; }
        public int Dias { get; set; }
        [Display(Name = "Zona")]
        public int IdZona { get; set; }
        [Required]
        public bool? Estado { get; set; }

        [ForeignKey("IdZona")]
        [InverseProperty("Remesa")]
        [Display(Name = "Zona")]
        public virtual Zona IdZonaNavigation { get; set; }
        [InverseProperty("IdRemesaNavigation")]
        public virtual ICollection<Programacion> Programacion { get; set; }
        [InverseProperty("IdRemesaNavigation")]
        public virtual ICollection<WayBill> WayBill { get; set; }
    }
}