// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    [Authorize]
    public partial class SubOficina
    {
        public SubOficina()
        {
            Users = new HashSet<Users>();
            Bodega = new HashSet<Bodega>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }
        [Required]
        [StringLength(50)]
        public string Encargado { get; set; }

        [Display(Name = "Teléfono del Encargado")]
        [Required]
        [StringLength(14)]
        public string TelefonoEncargado { get; set; }

        [Display(Name = "Activo")]
        public bool? Estado { get; set; }


        [Display(Name = "Bodega")]
        [InverseProperty("IdSubOficinaNavigation")]
        public virtual ICollection<Bodega> Bodega { get; set; }
        [InverseProperty("IdSubOficinaNavigation")]
        public virtual ICollection<Users> Users { get; set; }
        
    }
}