// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class WayBill
    {
        public WayBill()
        {
            WayBillDetalle = new HashSet<WayBillDetalle>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(20)]
        [Display(Name = "Código")]
        public string Codigo { get; set; }
        [Display(Name = "Remesa")]
        public int IdRemesa { get; set; }
        [Column(TypeName = "datetime")]
        [Display(Name = "Fecha de despacho")]
        public DateTime FechaDespacho { get; set; }
        [Display(Name = "Bodega")]
        public int IdBodega { get; set; }
        [Display(Name = "Activo")]
        public int Estado { get; set; }
        [Display(Name = "Año")]
        public int Year { get; set; }
        [Column(TypeName = "datetime")]
        [Display(Name = "Fecha de llegada")]
        public DateTime FechaLlegada { get; set; }
        [StringLength(500)]
        [Display(Name = "L.T.I")]
        public string IT { get; set; }
        [Required]
        [StringLength(40)]
        public string Nivel { get; set; }
        [Column(TypeName = "datetime")]
        [Display(Name = "Fecha de creación")]
        public DateTime? FechaCreacion { get; set; }
        [StringLength(450)]
        public string UsuarioCreacion { get; set; }

        [ForeignKey("IdBodega")]
        [InverseProperty("WayBill")]
        [Display(Name = "Bodega")]
        public virtual Bodega IdBodegaNavigation { get; set; }
        [ForeignKey("IdRemesa")]
        [InverseProperty("WayBill")]
        [Display(Name = "Remesa")]
        public virtual Remesa IdRemesaNavigation { get; set; }
        [InverseProperty("IdWayBillNavigation")]
        public virtual ICollection<WayBillDetalle> WayBillDetalle { get; set; }
    }
}