// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace prjbase.Models
{
    public partial class WayBillDetalle
    {
        public int Id { get; set; }
        [Display(Name ="WayBill")]
        public int IdWayBill { get; set; }
        [Display(Name = "Producto")]
        public int IdProducto { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Cantidad { get; set; }
        public string resultado { get; set; }
        public DateTime Fecha { get; set; }

        [ForeignKey("IdProducto")]
        [InverseProperty("WayBillDetalle")]
        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual Producto IdProductoNavigation { get; set; }
        [ForeignKey("IdWayBill")]
        [InverseProperty("WayBillDetalle")]
        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual WayBill IdWayBillNavigation { get; set; }
    }
}